#!/usr/bin/env bash


## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
#xset r rate 300 50 ## Get colors from .Xresources -------------------------------# xrdb ~/.Xresources
getcolors() {
	  FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	  BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	  BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	  RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	  GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	  YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	  BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	  MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	  CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	  WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors &

# Configurations --------------------------------------------#

workspaces &

bspc config ignore_ewmh_focus true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config window_gap 23
bspc config split_ratio 0.50
bspc config border_width 0

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 10

## Window rules ----------------------------------------------#

bspc rule -a Plank layer=above locked=on manage=off border=off focus=off state=floating


## Autostart -------------------------------------------------#

# Kill if already running
killall -9 sxhkd dunst ksuperkey xfce4-power-manager bspc plank &



# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Enable Dock
XDG_SESSION_DESKTOP=x11 plank &

# dhcp

#sudo dhcpcd &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Restore wallpaper

bash $HOME/.config/wpg/wp_init.sh &
xrdb merge $HOME/.Xresources &


# Start bspwm scripts
#autostart
#stcolors
autostart &
bspcomp &
bspbar &
bspfloat &
bspcolors &
bspdunst &
bsp-plankfloat &
